import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "my Gellary",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const TopNav = () => {
  return(
    <nav className=" flex items-center justify-between w-full text-xl border-b font-semibold p-4">
      <div>Gallery</div>
      <div>Sign In</div>
    </nav>
  )
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} flex flex-col gap-3`}>
      <body>
        <TopNav/>
        {children}
      </body>
    </html>
  );
}
